### ISSUE TITLE
Anti-Virus Blocked com.thjoeiaut.bitwarden.exe

### ISSUE THREAD

**Issue by WarrenKinley** [TheJoeIaut/Bitwarden-Streamdeck-Plugin#1]
Avast One has blocked com.thjoeiaut.bitwarden.exe since it contains IDP.Generic:

![image](https://github.com/TheJoeIaut/Bitwarden-Streamdeck-Plugin/assets/95749950/d92ac217-1b92-421d-87c7-7d47450e83d1)

**Comment by TheJoeIaut** [comment]
Hi,
Thanks for reporting, but I won't be able to Test/Whitelist all Anti Virus Tools out there.

I however did a check on https://www.virustotal.com/gui/file/c95a9398e11b0b3a7bb7e19ef96105a2a60a7d6be1cb5498c449cff4adf3c9aa/detection and it looks fine on all major Anti Virus Tools.

So your Warning is probably a false positive.

If you want to use the Plugin please Whitelist it locally on your machine.

BR TheJoeIaut
